VAEのコンポーネント作成
MLShukai/PrimitiveAMI pull request #104
Opened 2023-09-26 07:14 UTC by cehl-kurage

## 概要
#92 #93 #94 #95

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make test`コマンドでローカルにテストしましたか?
- [ ] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-26 11:36 UTC, cehl-kurage commented
実装ミスにつき修正中

2023-09-27 02:56 UTC, Geson-anko requested changes
@cehl-kurage 実装お疲れ様です。ConvTransposeの入出力計算面倒ですよね。難しいようでしたら私も手伝います。

`encode`メソッドや`decode`メソッドはそれぞれに`forward`として書いちゃっていいと思います。何か別な機能を実装する予定があれば、メソッドを分けた方がいいのですが、現状ただのエイリアスになっているので冗長かと

2023-09-27 02:56 UTC, Geson-anko commented on src/models/components/small_deconv_net.py
> +        """
英語にしてください。

2023-09-27 02:56 UTC, Geson-anko commented on src/models/components/small_deconv_net.py
> +    def init_output_size(self):
こういう複雑な事をするときはdocstringに何を行っているか概要を記述してください。できれば `_compute_input_shape`メソッドも **何のための計算なのか** 明記してください。

2023-09-27 02:56 UTC, Geson-anko commented on src/models/components/small_deconv_net.py
> +    def _compute_input_shape(
多分PyTorchのConvTranspose2dの、outputの計算式から逆関数を算出してやってるのだと思いますが、参照先があればそれを記載すると良いと思います。
https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html?highlight=convtranspose2d#torch.nn.ConvTranspose2d

ちなみにConvTransposeのサイズ I/Oの計算式は次のようになり、

$$
L_{out} = (L_{in} - 1) \times \text{stride} - 2 \times \text{padding} + \text{dilation} \times (\text{kernel size} - 1) + \text{output padding} + 1
$$

逆関数は output paddingを加味してこのようになります。

$$
L_{out} = \left\lfloor\frac{L_{in} + 2 \times \text{padding} - \text{dilation} \times (\text{kernel size} - 1) - 1 - \text{output padding}}{\text{stride}} + 1\right\rfloor
$$

2023-09-27 02:56 UTC, Geson-anko commented on tests/models/components/test_small_deconv_net.py
> +            (1, 256, 256, 3, 128, True, torch.nn.LeakyReLU(negative_slope=0.2)),
画像サイズが 128, 256, 512の場合でもテストしてください。

2023-09-27 03:24 UTC, cehl-kurage commented on src/models/components/observation_encoder/vae.py
> +    def __init__(self, small_conv_net: SmallConvNet, min_stddev=0.0):
ここが根拠でしたが、そのとおりなので修正します。  
https://github.com/openai/large-scale-curiosity/blob/master/auxiliary_tasks.py#L99C5-L99C5

2023-09-27 04:07 UTC, Geson-anko commented on src/models/components/small_deconv_net.py
> +        self.strides = ((2, 2), (2, 2), (3, 3))
多分 256に合わせるのが大変になってる場所として、strideが3なのが問題だと思う。1->2->4とか、2->2->4とかがいいのでは？正直ここら辺の実装の違いは仕方ないと思う。

2023-09-27 04:21 UTC, cehl-kurage commented on src/models/components/small_deconv_net.py
> +        self.strides = ((2, 2), (2, 2), (3, 3))
そうですね。そこで汎用性もなくなってると思うので、それでよければできると思います。  
承知しました。

2023-09-29 01:36 UTC, Geson-anko commented on tests/models/components/observation_encoder/test_vae.py
> +        assert isinstance(z_dist, torch.distributions.Normal)
```suggestion
        assert isinstance(z_dist, torch.distributions.Normal)
        assert z_dist.rsample().shape == (8, DIM_EMBED)
```

2023-09-29 01:40 UTC, Geson-anko approved these changes
@cehl-kurage OK! コンフリクト直しておきました。若干の修正はsuggestionからcommitしておきました。

2023-09-29 01:45 UTC, Geson-anko commented on tests/models/components/test_small_deconv_net.py
> +        assert mod.nl == torch.nn.ReLU()
等価表現は使えませんので、`isinstance`を用いましょう。
```suggestion
        assert isinstance(mod.nl, torch.nn.ReLU)
```

2023-09-29 01:45 UTC, Geson-anko commented
@cehl-kurage テスト落ちてるんで修正してくださいー

2023-09-30 02:37 UTC, merged