Feature/#93/vae data collector
MLShukai/PrimitiveAMI pull request #105
Opened 2023-09-26 10:47 UTC by cehl-kurage

## 概要
`VAEDataCollector`を実装しました。  
step record から観測だけを取り出し、保存します。

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make test`コマンドでローカルにテストしましたか?
- [ ] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-27 03:43 UTC, Geson-anko requested changes
@cehl-kurage お疲れ様です。 ファイル名やクラス名は `ObservationCollector`か`ObsDataCollector`にしましょう。そっちの方がわかりやすいです。

2023-09-27 03:43 UTC, Geson-anko commented on src/data_collectors/vae_data_collector.py
> +class VAEDataCollector(DataCollector):
VAEのために作られたクラスですが、クラス名はその機能を簡潔に表す名称にします。
```suggestion
class ObservationCollector(DataCollector):
```

2023-09-27 03:43 UTC, Geson-anko commented on tests/dara_collectors/test_vae_data_collector.py
> +        assert type(mod.get_data()) == torch.utils.data.TensorDataset
```suggestion
        assert isinstance(mod.get_data(), torch.utils.data.TensorDataset)
```

2023-09-29 01:31 UTC, Geson-anko commented on tests/dara_collectors/test_vae_data_collector.py
> +class TestVAEDataCollector:
```suggestion
class TestObsDataCollector:
```

2023-09-29 01:32 UTC, Geson-anko approved these changes
@cehl-kurage OK!

2023-09-29 11:18 UTC, myxyy approved these changes
大丈夫だと思います

2023-09-29 16:29 UTC, merged