VAELitModuleの実装
MLShukai/PrimitiveAMI pull request #107
Opened 2023-09-26 12:30 UTC by cehl-kurage

## 概要
#106   
LightningModule化します。VAE-encoder-decoderブランチの変更をマージで取り込んでいます

## 変更内容

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-29 16:24 UTC, myxyy approved these changes
大丈夫だと思います

2023-09-30 03:43 UTC, Geson-anko requested changes
@cehl-kurage お疲れ様です。一旦mainブランチをマージしてください。VAEEncoderとか名称が変わっていたりしますから。

2023-09-30 03:43 UTC, Geson-anko commented on src/models/vae_lit_module.py
> +        kl_loss = kl_divergence(z_dist, Normal(torch.zeros(z_shape), torch.ones(z_shape)))
ログをとってください。絶対。
```suggestion
        kl_loss = kl_divergence(z_dist, Normal(torch.zeros(z_shape), torch.ones(z_shape)))
        self.log("training/kl_loss", kl_loss)
        self.log("training/reconstruction_loss", rec_loss)
```

2023-09-30 03:43 UTC, Geson-anko commented on src/models/vae_lit_module.py
> +    def __init__(self, vae_net: VAE, optimizer: partial[Optimizer]):
kl損失に係数項をつけて調整可能にする必要があります。よくKL損失が強すぎて潜在空間が潰れてしまうことがよくあるので。
```suggestion
    def __init__(self, vae_net: VAE, optimizer: partial[Optimizer], kl_coef: float = 1.0):
```

```py
    def training_step(self, ...):
        loss = rec_loss + self.hparams.kl_coef * kl_loss
        return loss
```

2023-09-30 03:43 UTC, Geson-anko commented on tests/models/test_vae_lit_module.py
> +        assert type(loss) == torch.Tensor
lossのshapeが()であることを確認しないと損失計算時にエラー吐きます。`backward`呼んでおけば安心ですね。
```suggestion
        assert type(loss) == torch.Tensor
        assert loss.shape == ()
        loss.backward()
```

2023-11-02 09:05 UTC, Geson-anko requested changes
@cehl-kurage 若干修正あります。それ直したらマージしてください。

2023-11-07 04:43 UTC, merged