SimplePLTrainerの実装
MLShukai/PrimitiveAMI pull request #110
Opened 2023-09-27 13:10 UTC by myxyy

## 概要

https://github.com/MLShukai/PrimitiveAMI/pull/109

## 変更内容

* ForwardDynamicsTrainer
* InverseDynamicsTrainer
* PPOTrainer
をSimplePLTrainerのエイリアスに置き換え

各テストを複数回train検証するよう修正

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-27 14:53 UTC, Geson-anko requested changes
@myxyy お疲れ様です。PPOTrainerの修正お願いします。mainブランチとconflictしていますが、こちらのブランチの内容で上書きしてください。

2023-09-27 14:53 UTC, Geson-anko commented on src/trainers/ppo_trainer.py
> +PPOTrainer = SimplePLTrainer
PPOTrainerだけエイリアスではなく、実装の改変をお願いします。

```suggestion
class PPOTrainer(SimplePLTrainer):
    data_collector: DynamicsDataCollector
    def train(self):
       super().train()
       self.data_collector.clear()
```

2023-09-27 14:57 UTC, myxyy commented on src/trainers/ppo_trainer.py
> +PPOTrainer = SimplePLTrainer
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/110/commits/bec08433e922923f99a57e7ee3e633ace6032448

2023-09-28 01:44 UTC, Geson-anko commented
@myxyy なぜか `ppo_trainer`の単体テストだけを実行するとnanを吐きまくって落ちるんですよね

## 再現方法
```bash
poetry run pytest -vv tests/trainers/test_ppo_trainer.py
```

## 出力

```
self = <tests.trainers.test_ppo_trainer.TestPPOTrainer object at 0x7f3ca32e0370>
ppo_trainer = <src.trainers.ppo_trainer.PPOTrainer object at 0x7f3ca32e1bd0>

    def test_ppo_trainer(self, ppo_trainer: PPOTrainer):
>       ppo_trainer.train()

tests/trainers/test_ppo_trainer.py:96: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/trainers/ppo_trainer.py:10: in train
    super().train()
src/trainers/simple_pl_trainer.py:28: in train
    self.pl_trainer.fit(self.module, dataloader)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:532: in fit
    call._call_and_handle_interrupt(
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:43: in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:571: in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:980: in _run
    results = self._run_stage()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1023: in _run_stage
    self.fit_loop.run()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:202: in run
    self.advance()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:355: in advance
    self.epoch_loop.run(self._data_fetcher)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py:133: in run
    self.advance(data_fetcher)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py:219: in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:188: in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:266: in _optimizer_step
    call._call_lightning_module_hook(
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:146: in _call_lightning_module_hook
    output = fn(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/core/module.py:1276: in optimizer_step
    optimizer.step(closure=optimizer_closure)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py:161: in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py:231: in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py:116: in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/optim/optimizer.py:280: in wrapper
    out = func(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/optim/optimizer.py:33: in _use_grad
    ret = func(self, *args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/optim/adam.py:121: in step
    loss = closure()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py:103: in _wrap_closure
    closure_result = closure()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:142: in __call__
    self._result = self.closure(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/utils/_contextlib.py:115: in decorate_context
    return func(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:128: in closure
    step_output = self._step_fn()
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py:315: in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:294: in _call_strategy_hook
    output = fn(*args, **kwargs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py:380: in training_step
    return self.model.training_step(*args, **kwargs)
src/models/ppo_lit_module.py:124: in training_step
    output = self.model_step(batch)
src/models/ppo_lit_module.py:70: in model_step
    new_action_dist, new_values = self.forward(obses)
src/models/ppo_lit_module.py:54: in forward
    return self.net(obs)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/nn/modules/module.py:1501: in _call_impl
    return forward_call(*args, **kwargs)
src/models/components/policy_value_common_net.py:24: in forward
    return self.policy(x), self.value(x)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/nn/modules/module.py:1501: in _call_impl
    return forward_call(*args, **kwargs)
src/models/components/policy/normal_stochastic_policy.py:20: in forward
    norm_dist = distributions.normal.Normal(mean, std)
/home/rog/miniforge3/envs/pami/lib/python3.10/site-packages/torch/distributions/normal.py:56: in __init__
    super().__init__(batch_shape, validate_args=validate_args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Normal(loc: torch.Size([1, 128]), scale: torch.Size([1, 128])), batch_shape = torch.Size([1, 128]), event_shape = torch.Size([])
validate_args = None

    def __init__(
        self,
        batch_shape: torch.Size = torch.Size(),
        event_shape: torch.Size = torch.Size(),
        validate_args: Optional[bool] = None,
    ):
        self._batch_shape = batch_shape
        self._event_shape = event_shape
        if validate_args is not None:
            self._validate_args = validate_args
        if self._validate_args:
            try:
                arg_constraints = self.arg_constraints
            except NotImplementedError:
                arg_constraints = {}
                warnings.warn(f'{self.__class__} does not define `arg_constraints`. ' +
                              'Please set `arg_constraints = {}` or initialize the distribution ' +
                              'with `validate_args=False` to turn off validation.')
            for param, constraint in arg_constraints.items():
                if constraints.is_dependent(constraint):
                    continue  # skip constraints that cannot be checked
                if param not in self.__dict__ and isinstance(getattr(type(self), param), lazy_property):
                    continue  # skip checking lazily-constructed args
                value = getattr(self, param)
                valid = constraint.check(value)
                if not valid.all():
>                   raise ValueError(
                        f"Expected parameter {param} "
                        f"({type(value).__name__} of shape {tuple(value.shape)}) "
                        f"of distribution {repr(self)} "
                        f"to satisfy the constraint {repr(constraint)}, "
                        f"but found invalid values:\n{value}"
                    )
E                   ValueError: Expected paramet [...]

2023-09-28 12:23 UTC, myxyy commented
Approveいただいたのでひとまずマージしますね

2023-09-28 12:23 UTC, merged