IntervalAdjustorの作成
MLShukai/PrimitiveAMI pull request #12
Opened 2023-08-29 11:16 UTC by cehl-kurage

## 概要
#11 
feature番号間違えました...

## 変更内容
wip

## 影響範囲
wip

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make test`コマンドでローカルにテストしましたか?
- [ ] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-08-29 12:25 UTC, myxyy approved these changes
大丈夫だと思います

2023-08-30 02:36 UTC, Geson-anko commented on src/environment/interval_adjustor.py
> +class IntervalAdjustor(metaclass=ABCMeta):
基底から抽象クラスを定義する場合はこちらの書き方が主流ですが、本質的には同じ機能と意味を持つので修正しなくて大丈夫です。
```suggestion
from abc import ABC, abstractmethod
from time import perf_counter


class IntervalAdjustor(ABC):
```

2023-08-30 02:40 UTC, Geson-anko commented on src/environment/interval_adjustor.py
> +        self._start_time = perf_counter()
こっちの書き方の方が良いと言えば、良いです。
```suggestion
import math
class IntervalAdjustor(metaclass=ABCMeta):
    _start_time: float = -math.inf
    def __init__(self, interval: float) -> None:
        self.reset()
```

2023-08-30 02:42 UTC, Geson-anko requested changes
`__init__.py`がないです。一部コメントしていますが、好みの問題なので修正はしなくても構いません。

2023-08-30 04:02 UTC, Geson-anko commented
@cehl-kurage ブランチの切り方は `feature/#11/~`ですので、気をつけて

2023-08-30 14:42 UTC, cehl-kurage commented on src/environment/interval_adjustor.py
> +class IntervalAdjustor(metaclass=ABCMeta):
myxyさんの実装がこうだったんで、見慣れないなりにやった感じすね

2023-08-31 04:24 UTC, Geson-anko approved these changes
GOOD!

2023-08-31 04:24 UTC, merged