SpiralConvによる時系列学習試験導入
MLShukai/PrimitiveAMI pull request #124
Opened 2023-10-03 16:50 UTC by myxyy

## 概要

時系列処理を試しに実装しました
一応動きますが迷路でforward_dynamicsのlossが1e-4台になるとかなんか様子がおかしい

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を`make test`コマンドでローカルにテストしましたか?
- [ ] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-10-04 11:27 UTC, Geson-anko requested changes
@myxyy SpiralConvの変更は受け入れようと思いますが、論文にはかけないと思います。参考文献がちゃんと無いというのもありますが、今回の研究でまとめる範囲から外れてしまうことが原因です。

でも時系列モデル適用はめっちゃ気になるのでやるだけやってみたいです。

## 型ヒントに関して
関数における型ヒントは絶対忘れないでください。そこさえ守ればPythonコードはかなり健全に保てます。

## テストに関して
モデルに関しては、最上位のファイルのみデータが流れるかテストしてください。
- spiral_conv.Architecture
- SpiralConvForwardDynamics

## 学習に関して
若干の分散は大きくなるかもしれませんが、epochごとに隠れ状態はリセットしたほうがよいかもしれません。複数epoch回そうとするとダイナミクスがループしてしまいます。

2023-10-04 11:27 UTC, Geson-anko commented on configs/trainers_builder/inverse_time_series_forward_ppo.yaml
これは #123 でも使われている experimentコンフィグを使ってオーバーライドしましょう。

2023-10-04 11:27 UTC, Geson-anko commented on src/models/components/spiral_conv.py
> +    def get_hidden(self) -> (Tensor, Tensor):
型ヒントはこっちじゃないと正常に動かないようです。
```suggestion
    def get_hidden(self) -> tuple[Tensor, Tensor]:
```

2023-10-04 11:27 UTC, Geson-anko commented on src/models/components/spiral_conv.py
> +            block.set_hidden(hidden)
`pop(0)`はメモリの配置換えがおきるので高負荷です。よってアイテムアサインメントを使用してください。
```suggestion
        for idx, block in enumerate(self.block_list):
            block.set_hidden(hidden_list[i])
```

2023-10-04 11:27 UTC, Geson-anko commented on src/models/components/spiral_conv.py
> +    def forward(self, x):
```suggestion
    def forward(self, x: Tensor):
```

2023-10-04 11:27 UTC, Geson-anko commented on src/models/components/spiral_conv.py
> +    def set_is_refresh(self, is_refresh):
```suggestion
    def set_is_refresh(self, is_refresh: bool):
```

2023-10-04 11:27 UTC, Geson-anko commented on src/models/time_series_forward_dynamics_lit_module.py
> +        self.last_hidden = self.forward_dynamics_net.get_hidden()
ここのロジックがイマイチわかんないです。どういった理論で学習が行われるのかドキュメントに記してください。

2023-10-04 11:27 UTC, Geson-anko commented on src/trainers/time_series_forward_dynamics_trainer.py
いつかTrainerをカスタマイズするためにエイリアスを貼っておくのはアリですが、正直現在は冗長だと思います。
この間エイリアスを貼った理由は変更を最小限に抑えるための工夫でした。

2023-10-04 11:27 UTC, Geson-anko commented on src/models/components/forward_dynamics/spiral_conv_forward_dynamics.py
> +    def get_hidden(self) -> [(Tensor, Tensor)]:
```suggestion
    def get_hidden(self) -> list[tuple[Tensor, Tensor]]:
```

2023-10-04 15:54 UTC, myxyy commented on src/data_collectors/time_series_data_collector.py
> +            self.next_observations.pop(0)
dequeにしました  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/3ddf4601933d489e8eee935776d88659b896f260  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/ad24875d04a534bdfa639df016f396379a0c4001

2023-10-04 15:56 UTC, myxyy commented on src/data_collectors/time_series_data_collector.py
> +
クリアするようにしました  
学習の連続性が切れますが…データセットが十分長く取れることとトレードオフと考えることにします  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/c2e24847cbb39258fb9568920035a35bed1f82a4

2023-10-04 15:59 UTC, myxyy commented on src/models/components/spiral_conv.py
> +    def set_is_refresh(self, is_refresh):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/a83088586594e713be48c9f3167c2de6c903c8ab

2023-10-04 16:00 UTC, myxyy commented on src/models/components/spiral_conv.py
> +    def forward(self, x):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/af5a8b18fc30687e893a0373d7e558cd8773d3f9

2023-10-04 16:00 UTC, myxyy commented on src/models/components/spiral_conv.py
> +            block.set_hidden(hidden)
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/94ba6a2536a6c64cdabc5bb32af5a980ce9557b5

2023-10-04 16:01 UTC, myxyy commented on src/models/components/spiral_conv.py
> +    def get_hidden(self) -> (Tensor, Tensor):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/592eca693a38408767fb72648543d6c34dfe3e38

2023-10-07 01:48 UTC, myxyy commented on configs/trainers_builder/inverse_time_series_forward_ppo.yaml
experiment=time_seriesで実行できるようにしました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/2904aa14c0267f686b7d226235d401dab8cee7f4

2023-10-07 01:49 UTC, myxyy commented
* spiral_conv.Architecture
* SpiralConvForwardDynamics
のテストを追加しました  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/3688dcc457c155163ef23e827049d24ac8a34830  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/8597436a1d7e4fb217687b3cdc111f7250be8019

2023-10-14 10:38 UTC, Geson-anko requested changes
@myxyy レビューが遅れましたが、若干のロジック修正をしたらそのままマージして大丈夫かと思います。

2023-10-14 10:38 UTC, Geson-anko commented on configs/train.yaml
> +  - data_collector: dict_time_dynamics_trajectory
戻してください。
```suggestion
  - data_collector: dict_dynamics_trajectory
```

2023-10-14 10:38 UTC, Geson-anko commented on src/data_collectors/time_series_data_collector.py
> +
@myxyy 学習の連続性について質問です。データセットを毎回クリアすると、例えばロールアウトステップ数が1の時に、常に1つのデータで更新することになるので、学習の分散が大きくなり収束などに問題はありませんか？

2023-10-14 10:38 UTC, Geson-anko commented on src/models/time_series_forward_dynamics_lit_module.py
> +        self.last_hidden = self.forward_dynamics_net.get_hidden()
おそらく更新前の内部状態を更新後に引き継ぎたいのですよね？
ならば、trainingの初めに取得しておいて、終了後に再セットすると良いと思います。ただ、epochごとにhiddenをクリアしないと学習データが時間ループしてしまうのでそこは注意が必要です。
```suggestion
    def on_train_start(self):
        self.current_hidden = self.forward_dynamics_net.get_hidden()

    def on_train_epoch_start(self):
        self.forward_dynamics_net.reset_hidden()

    def on_train_end(self):
        self.last_hidden = self.forward_dynamics_net.get_hidden()
        self.forward_dynamics_net.set_hidden(self.current_hidden)
```

2023-10-16 12:14 UTC, myxyy commented on configs/train.yaml
> +  - data_collector: dict_time_dynamics_trajectory
戻しました https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/2814c8bed8fb63e489b4688d6f2628164415a048

2023-10-16 12:25 UTC, myxyy commented on src/models/time_series_forward_dynamics_lit_module.py
> +        self.last_hidden = self.forward_dynamics_net.get_hidden()
このあたりlast_hiddenの扱いに明らかなミスがあり何をしたかったのかちょっと思い出せないんですが  
内部状態の引継ぎをしたいという点はそのとおりなので現在の実装に基づけば提案していただいたようにepoch毎にreset_hiddenしてon_train_endで状態を元に戻すのがよいと思います  
修正しました  
https://github.com/MLShukai/PrimitiveAMI/pull/124/commits/549e2839e9e4d1477b9e60ac103d8f2c0a7cee94

2023-10-16 13:43 UTC, myxyy commented on src/data_collectors/time_series_data_collector.py
> +
学習の連続性というのは学習データの始点に対応する内部状態をセットするのが実装上難しいという話でした

分散についてはどうでしょうね、あまり深く理解できているわけではないですがadvantageを用いたA2Cでは方策勾配の係数の分散はベースライン=価値関数の性能に依存するものと理解していて、データ自体の分散は強化学習の文脈というよりは一般的なNNのバッチ数とかの話の気がしてます

2023-10-17 08:09 UTC, Geson-anko approved these changes
@myxyy GOOD! プルリクエストをオープンしてマージしてください。

2023-10-17 13:09 UTC, merged