Feature/#15/implement actor critic
MLShukai/PrimitiveAMI pull request #16
Opened 2023-08-29 16:26 UTC by myxyy

## 概要

https://github.com/MLShukai/PrimitiveAMI/issues/15
重みを共有するActor-Criticのネットワーク実装

## 変更内容

* 抽象クラスStochasticPolicy
  - 継承クラスNormalStochasticPolicy
* 抽象クラスValue
  - 継承クラスFullyConnectValue
* クラスPolicyValueCommonNet
を追加

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-08-30 02:55 UTC, Geson-anko requested changes
ありがとうございます。大体できてきましたね。
1. `__init__.py`を忘れずに。
2. `policy_value_common_net/policy_value_common_net.py`というフォルダ構造は冗長なので`src/models/components/policy_value_common_net.py`としてください。
3. フォルダ名`stochastic_policy` を`policy`フォルダに変更してください。決定的方策もおきましょう。(Delta分布を使ってね)
4. 今回の変更に合わせてテストのフォルダ構造も修正してください。

2023-08-30 02:55 UTC, Geson-anko commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        )
Dependency Injectionかけてください。
```suggestion
    def __init__(self, base_model: nn.Module, policy: StochasticPolicy, value: Value, height: int, width: int, dim_hidden: int):
        super().__init__()
        self.policy = policy
        self.value = value
        self.base_model = base_model
```

2023-08-30 02:55 UTC, Geson-anko commented on src/models/components/stochastic_policy/normal_stochastic_policy.py
> +        std = self.relu(self.fc_std(input)) + 1e-7  # 0だとエラーなる
`softplus`がよく使われます。コメントに日本語は文字コード問題を起こす恐れがあるのでできれば避けてください。
```suggestion
        std = torch.softplus(self.fc_std(input)) + 1e-7  # Avoid 0 error.
```

2023-08-30 02:55 UTC, Geson-anko commented on tests/models/components/stochastic_policy/test_normal_stochastic_policy.py
> +    assert dist.rsample().size() == (batch, dim_out)
戻り値の型が特殊なので型チェックもお願いします。
```suggestion
    assert isinstance(dist, Distribution)
    assert dist.rsample().size() == (batch, dim_out)
```

2023-08-30 14:30 UTC, myxyy commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        )
base_modelが他クラスと共有されるようなことがないのであればPolicyValueCommonNetを抽象クラスとしてConv2d等実装は継承したクラスでやってもよいかとも思いましたがどうでしょうか

2023-08-30 14:32 UTC, myxyy commented on tests/models/components/stochastic_policy/test_normal_stochastic_policy.py
> +    assert dist.rsample().size() == (batch, dim_out)
チェックするようにしました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/eda74920457b412fc5e50572af7e8af4775edadf

2023-08-31 04:16 UTC, Geson-anko commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        )
@myxyy 継承先でやる提案はOKです。そうしてください。
ただ、モデルの構造を後から変化させたい場合に現在の直書きするやり方は好まれません。また、InverseDynamicsを作る過程で、`CNNObservationEncoder`を実装しており、内部構造がほとんどそれと一致しています。それを再利用可能な構造にするべきだと思います。

2023-08-31 04:19 UTC, Geson-anko commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        x = self.conv2d3(x)
ここ活性化関数忘れてますし、やはりモデルの詳しい実装は分けた方がミスも減って安全です。

2023-08-31 04:21 UTC, Geson-anko commented
@myxyy TanhNormal使ったPolicyの実装もしておきたいです。そこまでお願いします。

2023-08-31 12:19 UTC, myxyy commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        x = self.conv2d3(x)
SmallConvNetとして分けました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/7f7abed66b6ce4de97d9c4931ddb5e111760aa4e

2023-08-31 12:20 UTC, myxyy commented on src/models/components/policy_value_common_net/policy_value_common_net.py
> +        )
Conv部分を再利用するようならばDIの方が良いですね
SmallConvNetをutilsに作りDIするようにしました  
https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/7f7abed66b6ce4de97d9c4931ddb5e111760aa4e  
https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/605936b22a3a5c48eb5829e322e6c27d8c965d4f

2023-08-31 12:29 UTC, myxyy commented
> @myxyy TanhNormal使ったPolicyの実装もしておきたいです。そこまでお願いします。

追加しました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/37c37683fcf8f5b7a8f5202f493a20a5287c66e9

2023-09-01 07:35 UTC, Geson-anko requested changes
@myxyy ありがとうございます。この修正でApproveです。
1. TanhNormalの修正
2. DeterministicPolicyは使うことがないので削除して良い。
3. utils.pyは`small_conv_net.py`にしてください。

2023-09-01 07:35 UTC, Geson-anko commented on src/models/components/policy/deterministic_stochastic_policy.py
> +class DeterministicStochasticPolicy(StochasticPolicy):
決定的確率的方策は流石に矛盾してますね.. `DeterministicPolicy`でいいです。
このクラスは別になくても良いですが、互換性的な問題であってもいいかもしれないとは考えてます。正直使う予定は一切ないです。

一応 `log_prob`は常に0ですし、`entropy`も常に0なのでPPOで決定的方策を学習するのは厳しいかもしれませんね...

ちなみに torchrlのDeltaはlog_probが常にinfな上にentropyの実装がされていないので間違っている上に使い物にならないです。

2023-09-01 07:35 UTC, Geson-anko commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +
エントロピー計算の参照を実装に入れておいてください。PPOの更新で使います。
```suggestion
from torchrl.modules import TanhNormal as _TanhNormal

class TanhNormal(_TanhNormal):
    def entropy(self):
        self.base_dist.entropy()
```

2023-09-01 07:35 UTC, Geson-anko commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +    def forward(self, input: Tensor) -> Distribution:
正確な返り値の型
```suggestion
    def forward(self, input: Tensor) -> TanhNormal:
```

2023-09-01 07:35 UTC, Geson-anko commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +        tanh_norm_dist = torchrl.modules.TanhNormal(mean, std)
元々の実装だとTanhNormalは-5 ~ 5の範囲なんですよね。なのでちょっと修正です。https://pytorch.org/rl/reference/generated/torchrl.modules.TanhNormal.html
```suggestion
        tanh_norm_dist = TanhNormal(mean, std, upscale=1.0)
```

2023-09-01 16:34 UTC, myxyy commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +    def forward(self, input: Tensor) -> Distribution:
変更しました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/e3e1ef61cd1d66fd83e50c8caabcde393229f614

2023-09-01 16:34 UTC, myxyy commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +        tanh_norm_dist = torchrl.modules.TanhNormal(mean, std)
設定しました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/f23d77a0be29593299207a7bf30c8105c16e42cb

2023-09-01 16:35 UTC, myxyy commented on src/models/components/policy/tahh_normal_stochastic_policy.py
> +
対応しました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/0904e98281aea93ddfdab97f690661310ee8bcc1

2023-09-01 16:35 UTC, myxyy commented on src/models/components/policy/deterministic_stochastic_policy.py
> +class DeterministicStochasticPolicy(StochasticPolicy):
DeterministicStochasticPolicyを削除しました https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/d0d8ec731e6df7be410d568a98cca3f81f7b41d9

2023-09-01 16:36 UTC, myxyy commented
> @myxyy ありがとうございます。この修正でApproveです。
> 
> 1. TanhNormalの修正
> 2. DeterministicPolicyは使うことがないので削除して良い。
> 3. utils.pyは`small_conv_net.py`にしてください。

コメント対応しました

2023-09-02 03:10 UTC, Geson-anko approved these changes
@myxyy PolicyValueCommmonNetの引数に `width`, `height`とかが残ってたので消しました。
https://github.com/MLShukai/PrimitiveAMI/pull/16/commits/bbdf63b2bfc7b6a8e14f035a00d48e7ae2423035

2023-09-02 03:17 UTC, merged