DynamicsDataCollectorの実装
MLShukai/PrimitiveAMI pull request #53
Opened 2023-09-07 15:27 UTC by myxyy

## 概要

https://github.com/MLShukai/PrimitiveAMI/issues/50

## 変更内容

DynamicsDataCollector、DummyDynamicsDataCollector及びテスト追加

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-08 05:34 UTC, Geson-anko requested changes
@myxyy あまり複雑な実装にする予定はありませんが、データの保存方法について議論が必要です。

InverseDynamicsの学習用データはAMI活動全体を通して使い続けることができます。一度更新した後に捨てると分散が大きくなる恐れがあります。最大バッファサイズを定め、それを満たした後は確率Pでバッファのランダムな位置を置き換える、と言った実装が求められます。

2023-09-08 05:34 UTC, Geson-anko commented on src/data_collectors/dummy_dynamics_data_collector.py
> +    def __init__(self, action_dim, observation_dim):
- 引数はshapeにしておくと汎用性が出ます。観測は特に画像ですし。
- コンストラクタの引数に、`get_data`で返すデータ数を指定してください。また、`collect`でbatchを増やすのはダミークラスの機能として冗長かつ明示性が失われるため空の関数に置き換えてください。


- 引数の型アノテーションは全てにおいて忘れないでください。入出力の関係は他の処理に影響しますから、必ず明示する必要があります。
```suggestion
    def __init__(self, size: int,  action_shape: tuple[int], observation_shape: tuple[int]):
```

2023-09-08 05:34 UTC, Geson-anko commented on src/data_collectors/dynamics_data_collector.py
> +        self.next_observations = []
- InveseDynamicsのデータセットはリセットする必要がなく、AMIの活動全体を通して使い続けることができます。
```suggestion
    def get_data(self) -> (Tensor, Tensor, Tensor, Tensor):
        prev_actions = torch.stack(self.prev_actions)
        observations = torch.stack(self.observations)
        actions = torch.stack(self.actions)
        next_observations = torch.stack(self.next_observations)
```

2023-09-08 12:00 UTC, myxyy commented on src/data_collectors/dummy_dynamics_data_collector.py
> +    def __init__(self, action_dim, observation_dim):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/53/commits/b2fa5014a6e406b45d97bd2d2e8041f02c7730fb

2023-09-08 12:01 UTC, myxyy commented on src/data_collectors/dynamics_data_collector.py
> +        self.next_observations = []
https://www.notion.so/911e4788afab4c0798406b31c51a2500?pvs=4#cd9888bf9eeb4b4a95ca5b9ca6ad4590
に従い確率的に消滅するようにしました https://github.com/MLShukai/PrimitiveAMI/pull/53/commits/4a4568ef921f17cc08960c2f27c99f3123475b05

2023-09-08 12:07 UTC, Geson-anko commented on src/data_collectors/dummy_dynamics_data_collector.py
> +    def __init__(self, action_dim, observation_dim):
@myxyy 引数を`*_dim`から`*_shape`に変更するの忘れてますよ

2023-09-08 12:51 UTC, Geson-anko requested changes
@myxyy お疲れ様です。修正お願いします。
- `collect`メソッドの仕様について
  - バッファが満杯でないときは常に保存する
  - バッファが満杯の場合はランダムな位置を、新しいデータで置き換えます。
- `get_data`メソッドの戻り値の型は`Dataset`型に統一します。

2023-09-08 13:29 UTC, myxyy commented on src/data_collectors/dynamics_data_collector.py
> +        return return_list
よく考えるとそうですね  
この処理は消します

2023-09-08 13:31 UTC, myxyy commented on src/data_collectors/dummy_dynamics_data_collector.py
> +        return prev_actions, observations, actions, next_observations
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/53/commits/b821055b7741d3ca039937a0e91079b6564cf79c

2023-09-08 13:31 UTC, myxyy commented on src/data_collectors/dummy_dynamics_data_collector.py
> +        return prev_actions, observations, actions, next_observations
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/53/commits/b821055b7741d3ca039937a0e91079b6564cf79c

2023-09-08 13:32 UTC, myxyy commented on src/data_collectors/dynamics_data_collector.py
> +        self.next_observations.append(step_record[RK.NEXT_OBSERVATION])
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/53/commits/52e1ed537859b066bf8aabfb78f027f65a63a1e6

2023-09-09 05:17 UTC, Geson-anko approved these changes
@myxyy お疲れ様です。ありがとうございます。
ちょっとした修正はありますが、commit suggestionで追加しておけば問題ないレベルだと思います。

2023-09-09 05:17 UTC, Geson-anko commented on tests/dara_collectors/test_dummy_dynamics_data_collector.py
> +    prev_actions, observations, actions, next_observations = dummy_dynamics_data_collector.get_data()[0:get_size]
正確に`get_size`分取れてるか修正
```suggestion
    prev_actions, observations, actions, next_observations = dummy_dynamics_data_collector.get_data()[:]
```

2023-09-09 07:19 UTC, merged

2023-09-10 08:58 UTC, Geson-anko commented on src/data_collectors/dynamics_data_collector.py
> +            self.next_observations[rand_ind] = step_record[RK.NEXT_OBSERVATION].clone().cpu()
ここ`np.random.randint`じゃないと動かないです。そしてテストでもここのブロックが呼ばれてないのでしっかりと呼ぶようにテストし直してください。

2023-09-10 08:59 UTC, Geson-anko commented on tests/dara_collectors/test_dynamics_data_collector.py
> +        (176, (134,), (51,)),
`max_size`に128よりも小さい値を設定して、再度テストください。