ForwardDynamicsTrainer実装
MLShukai/PrimitiveAMI pull request #63
Opened 2023-09-10 12:56 UTC by myxyy

## 概要

https://github.com/MLShukai/PrimitiveAMI/issues/61

## 変更内容

ForwardDynamicsLitModuleとForwardDynamicsTrainerの実装

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-11 15:03 UTC, cehl-kurage requested changes
仕様に従ってるか中心に見ましたー

2023-09-12 00:53 UTC, myxyy commented on src/models/components/forward_dynamics/forward_dynamics_lit_module.py
> +        return self.optimizer
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/63/commits/621d9d26ce19fa198cad6db35f8b83121ac462ad

2023-09-12 00:53 UTC, myxyy commented on src/models/components/forward_dynamics/forward_dynamics_lit_module.py
> +    def __init__(self, obs_encoder: ObservationEncoder, forward_dynamics_net: ForwardDynamics, optimizer: Optimizer):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/63/commits/621d9d26ce19fa198cad6db35f8b83121ac462ad

2023-09-12 00:53 UTC, myxyy commented on src/models/components/forward_dynamics/forward_dynamics_lit_module.py
> +        self.save_hyperparameters(logger=False)
削除しました https://github.com/MLShukai/PrimitiveAMI/pull/63/commits/555f03d65634b86f6b769982b571cd28f17c655b

2023-09-12 02:41 UTC, cehl-kurage approved these changes

2023-09-12 02:41 UTC, cehl-kurage commented
approved

2023-09-12 13:05 UTC, Geson-anko approved these changes
お疲れ様です。とても簡潔で良いと思いますが、余裕があれば改善してほしいところがあります。
1. テストの関数をクラスにまとめてください。`@pytest.fixture`をglobal定義すると、実はどのテストファイルからも呼び出し可能になる仕様となっています。そのため意図しない共有が起こる恐れがあり、それを防ぐために、クラスのテストはクラス化します。（関数のテストはglobalなfixtureの方が後々便利なのですが、、、）
```py
class TestClass:
    @pytest.fixture # Can use only in this class.
    def fixture(self):
        ...
    def test_hoge(self, fixture):
        ...
```
参考: https://github.com/MLShukai/PrimitiveAMI/blob/main/tests/models/test_ppo_lit_module.py

2. prefix `mock_`は`mocker.Mock`オブジェクトにのみ使用するため、Mockオブジェクトでないもののfixtureの名前から`mock_`prefixを外してください。
3. 本当は`pytest.mark.skipif(not torch.cuda.is_available(), reason="No CUDA device")`を使ってGPU上でちゃんと動くかテストしたいところです。でも動きそうなのでパスします。

2023-09-12 13:45 UTC, myxyy commented on tests/trainers/test_forward_dynamics_trainer.py
> +        max_epochs=1, logger=False, enable_checkpointing=False, enable_progress_bar=False, enable_model_summary=False
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/63/commits/b1b5f4fb71fcdc0a9fa23117601380260e58cb5f

2023-09-12 13:47 UTC, myxyy commented
テストをクラスにまとめ、mockじゃないやつは`mock_`外しました

2023-09-13 14:26 UTC, merged