PolicyValueCommonNetの構造を論文に合わせる
MLShukai/PrimitiveAMI pull request #97
Opened 2023-09-23 06:01 UTC by myxyy

## 概要

https://github.com/MLShukai/PrimitiveAMI/issues/96

## 変更内容

SmallConvNetとPolicy, Valueの線形層の間の2層の非線形層を追加  
次元数ハイパラの調整が必要そうであれば別途対応

## 影響範囲

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を`make test`コマンドでローカルにテストしましたか?
- [x] `make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-09-23 06:21 UTC, Geson-anko commented
論文実測って本当にこんな感じです？参照元を教えていただければ幸いです

2023-09-23 06:22 UTC, myxyy commented
https://github.com/openai/large-scale-curiosity/blob/e0a698676d19307a095cd4ac1991c4e4e70e56fb/cnn_policy.py#L34-L44  
対応箇所はこのあたりですね

2023-09-24 00:58 UTC, Geson-anko requested changes
@myxyy SmallConvNetの後にfcが２層入るのならば、SmallConvNetを継承してSmallConvNetFCPlus みたいな名前でbase_model側を新しいクラスで作ってくれませんか？（記述先のファイルは`small_conv_net.py` で大丈夫です）

というのも、多分原論文の実装はCNNPolicyとauxiliary task(Inv DynaやVAE) でモデルを共有しようと考えていたようですが、結局うまく行かなかったようで `features_shared_with_policy` が  `False` になってます。

InverseDynamicsやVAEが全てのロールアウト全体を通して学習データが集められるのに対して、PPO PolicyはOn-Policyな手法のためロールアウト一回ごとに学習データが全て変わります。それに学習するタスクの性質も、ただの誤差最小化と方策勾配法では全然違うので、多分モデルを共有しない方が確実に動くと思います。

https://github.com/openai/large-scale-curiosity/blob/master/run.py#L63-L66

2023-09-24 03:48 UTC, myxyy commented
FullyConnectedモジュールを追加してbase_modelはnn.Sequentialで作るようにしました

2023-09-24 05:39 UTC, Geson-anko requested changes
demoの方が多分バグって動かないのと、活性化関数のタイピングの修正お願いします。

2023-09-24 05:39 UTC, Geson-anko commented on demos/demo_agent_interaction.py
> +        FullyConnected(embed_dim, embed_dim, activation=nn.ReLU),
かっこ() 忘れてます
```suggestion
        FullyConnected(embed_dim, embed_dim, activation=nn.ReLU()),
```

2023-09-24 05:39 UTC, Geson-anko commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
Typeヒントは`Callable` です。あとはデフォルト値は`ReLU()`にしておくと便利かと。
```suggestion
    def __init__(self, dim_in: int, dim_out: int, activation: Callable[[Tensor], Tensor] = torch.relu):
```

2023-09-24 08:51 UTC, myxyy commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
修正しました https://github.com/MLShukai/PrimitiveAMI/pull/97/commits/e7baa40a0ea14638db0dafe381c2730965d3691f   
デフォルトはNone=恒等写像が自然かとも思いましたが

2023-09-24 08:51 UTC, myxyy commented on demos/demo_agent_interaction.py
> +        FullyConnected(embed_dim, embed_dim, activation=nn.ReLU),
デフォルトをReLUにしたので消しました https://github.com/MLShukai/PrimitiveAMI/pull/97/commits/e7baa40a0ea14638db0dafe381c2730965d3691f

2023-09-24 11:53 UTC, Geson-anko approved these changes
@myxyy LGTM!

2023-09-24 12:13 UTC, Geson-anko commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
恒等写像をNoneにした時はもはや`nn.Linear`と全く等価なので実装する必要性が薄いかと思います

2023-09-24 12:20 UTC, merged

2023-09-24 13:35 UTC, Geson-anko commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
@myxyy なるほど、モノイドについてはよくわかっていませんが、リファクタリングや再設計時に参考にさせていただきたいです。ていうか良い性質はどのようなものなのでしょう？

2023-09-24 14:26 UTC, myxyy commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
今回のケースではモノイドの話はあまり関係ないですが、"何もしない"操作は他の概念（今回だとrelu）に依存せずに存在するためデフォルトの値として適切と考えられます（数学だと**自然に定まる**とか表現される）  
今回の場合の良い性質の具体例はちょっと思いつくのが難しいですが、**余談**に書いているように恒等操作や単位元といった"何もしない"操作を特別視するメリットは確かにあるはずで、そのベストプラクティスを踏襲した形です  
率直な話では線形層とReLU関数というのは本来何の関係もないはずで、そこでReLUがデフォルト値として特別視されるのは気持ち悪い感覚があります

### 余談
モノイドの単位元は再帰的関数における基底ケースの引数として考えることが多いです  
例えば文字列$`x_1x_2\dots x_n`$は列の結合操作$`+`$に対してモノイドを成し、単位元は空列$`\varepsilon`$とした場合について考えます  
$(abc+def)+ghi=abc+(def+ghi)$や$`\varepsilon+abcd=abcd+\varepsilon=abcd`$が成り立つような世界ですね
このとき文字列のマージソートを考えると
```math
\begin{align}
{\rm mergesort}(\varepsilon) &= \varepsilon\\
{\rm mergesort}(s_1 + s_2)  &= {\rm merge}({\rm mergesort}(s_1), {\rm mergesort}(s_2))
\end{align}
```
のような擬似コードとなりこの$`{\rm mergesort}(\varepsilon) = \varepsilon`$が基底ケースです  
単位元は様々なシチュエーションで活用するため特別な名前を付けておく等で識別可能とすると便利です  
PyTorchでも[恒等写像の層](https://pytorch.org/docs/stable/generated/torch.nn.Identity.html#torch.nn.Identity)が定義されているようですね

2023-09-25 04:34 UTC, Geson-anko commented on src/models/components/fully_connected.py
> +    def __init__(self, dim_in: int, dim_out: int, activation: nn.Module = None):
@myxyy 確かに reluを特別視するのは気持ちが悪いですね。その感覚は非常に重要かと思われます。次回からはそのような実装を行う方針でいきましょう。